### ISSUE TITLE
web ui

### ISSUE THREAD

**Issue by shenzhen-xi** [temporalio/temporal-helm-charts#27]
Hi
would it be possible for you to add [temporal-web](https://github.com/temporalio/temporal-web) to the chart?

**Comment by markmark206** [comment]
@shenzhen-xi thank you for filing this!

Yes, this is coming, stay tuned!

**Comment by markmark206** [comment]
Thank you for creating this issue, @shenzhen-xi . 

I believe this to be done, thanks to @pauldemarco.
